# Generated by Django 5.1.3 on 2024-11-20 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Autor",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="Fecha",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
