# Generated by Django 5.1.3 on 2024-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0003_comentario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="usuario",
            new_name="autor",
        ),
        migrations.RenameField(
            model_name="comentario",
            old_name="fecha_creacion",
            new_name="fecha",
        ),
        migrations.AlterField(
            model_name="comentario",
            name="texto",
            field=models.TextField(max_length=1000),
        ),
    ]
