# Generated by Django 5.1.3 on 2024-11-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Titulo", models.CharField(max_length=100)),
                ("Descripcion", models.CharField(max_length=250)),
                ("Imagen", models.ImageField(upload_to="inicio/images")),
                ("Url", models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
