# Generated by Django 5.1.3 on 2024-11-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Reportes",
        ),
    ]
