# Generated by Django 5.1.3 on 2024-11-16 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0002_rename_post_reportes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombres", models.CharField(max_length=300)),
                ("Apellidos", models.CharField(max_length=300)),
                ("Contacto", models.CharField(max_length=300)),
                ("Descripcion", models.TextField(max_length=5000)),
                ("Imagen", models.ImageField(upload_to="reportes/images")),
                ("Fecha", models.DateField(verbose_name=datetime.date.today)),
                ("Estado", models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name="Reportes",
        ),
    ]
